# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrmlDaemon < Formula
  desc "Connect Mac/Linux to the trml iOS app via an E2E-encrypted relay"
  homepage "https://trml.app"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/craigderington/trml-daemon/releases/download/v0.1.1/trml-daemon_Darwin_x86_64.tar.gz"
      sha256 "1c7803fa4c70e0e108387dc0bae70520e36c4afd14fd8bf198a3a6dfdbefd629"

      define_method(:install) do
        bin.install "trml-daemon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/craigderington/trml-daemon/releases/download/v0.1.1/trml-daemon_Darwin_arm64.tar.gz"
      sha256 "801e8048f983ce746694082ba4f52d5c2720e465e09fc03b7b737eaba7a3aaae"

      define_method(:install) do
        bin.install "trml-daemon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/craigderington/trml-daemon/releases/download/v0.1.1/trml-daemon_Linux_x86_64.tar.gz"
      sha256 "edcc829441cae36c670aefd7634f801889c0b5254c4e4aedf282265d9917ed68"
      define_method(:install) do
        bin.install "trml-daemon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/craigderington/trml-daemon/releases/download/v0.1.1/trml-daemon_Linux_arm64.tar.gz"
      sha256 "cfd89bdddf593e7f66e9d83201b091dc6ab194bab192e81ead889186a3f1c8da"
      define_method(:install) do
        bin.install "trml-daemon"
      end
    end
  end

  def caveats
    <<~EOS
      Pair an iPhone, then install the background service:

        trml-daemon pair
        trml-daemon install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/trml-daemon --version")
  end
end
